pool:
  vmImage: 'windows-2019'

trigger:
  batch: true
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - /doc/**/*

variables:
  - group: 'External Resources'

steps:

- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: GitVersion
  inputs:
    preferBundledVersion: false

- task: petersendev.dotnet-global-tool-installer.DotnetGlobalToolInstaller.DotnetGlobalToolInstaller@0
  displayName: 'install sonar scanner'
  inputs:
    name: 'dotnet-sonarscanner'
    checkLatest: true

- task: DotNetCoreCLI@2
  displayName: 'begin SQ analysis'
  inputs:
    command: custom
    custom: sonarscanner
    arguments: 'begin /k:"aloneguid_storage" /o:"aloneguid-github" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="$(Sonar.Login)"'

- task: DotNetCoreCLI@2
  displayName: 'run integration tests'
  inputs:
    command: test
    projects: test/Storage.Net.Tests.Integration
    arguments: '-c debug'

- task: DotNetCoreCLI@2
  displayName: 'end analysis'
  inputs:
    command: custom
    custom: sonarscanner
    arguments: 'end /d:sonar.login="$(Sonar.Login)"'
    condition: succeededOrFailed()