pool:
  vmImage: 'windows-2019'

trigger:
  batch: true
  branches:
    include:
      - master

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - /doc/**/*

variables:
  - group: 'External Resources'

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@4
  displayName: GitVersion
  inputs:
    preferBundledVersion: false
- task: DotNetCoreCLI@2
  displayName: build
  inputs:
    projects: test/Storage.Net.Tests.Integration
    arguments: '-c release'
- task: DotNetCoreCLI@2
  displayName: 'run integration tests'
  inputs:
    command: test
    projects: test/Storage.Net.Tests.Integration
    arguments: '-c release -v d'